dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install coverage codecov
script:
  - python setup.py develop
  - coverage run -m unittest discover
  - codecov
matrix:
  fast_finish: true
